Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -186,6 +186,10 @@ jobs:
                   style: italic
           EOF
 
+      - name: Debug assets presence
+        run: |
+          ls -R assets || echo "assets folder not found"
+
       - name: Install dependencies
         run: flutter pub get
 
